import {mountShell,toast,isLocalDemo} from '/admin/_shell/admin-shell.js';
import {getSession} from '/admin/_shell/supabase.js';
import {esc} from '/admin/_shell/ui.js';
const ctx=await mountShell({title:'Acquisition'}),app=document.querySelector('#acquisition');
const view=new URLSearchParams(location.search).get('view')||'queue';
const header=`<header class="ws-head"><span class="ws-kicker">PlugVerse / Acquisition</span><h1>${view==='results'?'Compare what works.':view==='replies'?'Keep the conversation going.':'Good prospects. Less friction.'}</h1><p>Your Instagram + email lane and Karthik’s email / LinkedIn lane. One shared contact history, separate experiments.</p></header><nav class="ws-tools" aria-label="Acquisition sections"><a href="/admin/acquisition/">Sending queue</a><a href="/admin/acquisition/?view=replies">Replies & follow-ups</a><a href="/admin/acquisition/?view=results">Experiments & results</a></nav>`;
app.innerHTML=header+'<p role="status">Verifying the operational source…</p>';
let data;
try{
 if(isLocalDemo())data={connection:{state:'not_connected',reason:'Local design preview. Real board persistence is not connected.'}};
 else {const session=await getSession();const r=await fetch('/api/acquisition',{headers:{Authorization:`Bearer ${session?.access_token||''}`},cache:'no-store'});data=await r.json();if(!r.ok)throw new Error(data.error||'Connection unavailable');}
}catch(e){data={connection:{state:'unavailable',reason:e.message}};}
const c=data.connection;
app.innerHTML=header+`<section class="ws-card"><span class="ws-state warn">${c.state==='not_connected'?'Board not connected':'Connection unavailable'}</span><h2>Keep the current board as the owner.</h2><p>${esc(c.reason)}</p><p class="aq-notice">The saved snapshot is not current approval or a complete sending history. Until the board is reconciled, this workspace will not create prospects, record sends or show unknown results as zero.</p><a class="ws-link" href="https://claude.ai/artifact/5SoV39QXz4NghVwKvmzSN6" target="_blank" rel="noopener">Open your existing board ↗</a><p class="ws-provenance">Needed: current board source and complete stored history, then verified shared writes and contributor permissions.</p></section>`;
if(view==='results')app.innerHTML+=`<div class="ws-grid" style="margin-top:20px">${[['Cooper','Instagram + Email'],['Karthik','Email + LinkedIn']].map(([who,channel])=>`<section class="ws-card"><h2>${who} / ${channel}</h2><div class="ws-stat">—</div><p>Verified outcomes not connected.</p><ul class="ws-list">${['Unique first contacts','Replies / interested replies','Verified artist signups','First real gig use'].map(x=>`<li>${x}<span>Unknown</span></li>`).join('')}</ul></section>`).join('')}</div><p class="ws-note">Compare the same cohort window and report channel, sender and audience separately. The existing ?s=dm link proves channel only; it does not identify an individual sender or prospect.</p>`;
else if(view==='replies')app.innerHTML+=`<section class="ws-card" style="margin-top:20px"><h2>Follow-ups follow the conversation.</h2><p>Instagram: one follow-up after at least five days without a reply. Email: one after four days in the same thread. Any reply or decline stops that sequence.</p><p class="ws-note">LinkedIn cadence has not been approved. Inbox coverage is not connected; an empty list would not prove that nobody replied.</p></section>`;
else if(ctx.role==='full')app.innerHTML+=`<section class="ws-card" style="margin-top:20px"><h2>The sending flow</h2><p>Copy username, copy the sender-approved message, open Instagram, send, then confirm Sent. The app saves known details and advances only after verification.</p><div class="aq-controls"><button disabled>Copy username</button><button disabled>Copy approved draft</button><button disabled>Open profile</button><button disabled class="primary">Mark sent & next</button></div><p class="ws-provenance">Actions unlock only for a verified owner, current sender approval and an unsuppressed prospect. Opening or copying never counts as sending.</p></section>`;
void toast;
