import {mountShell,isLocalDemo} from '/admin/_shell/admin-shell.js';
import {getSession} from '/admin/_shell/supabase.js';
import {esc} from '/admin/_shell/ui.js';
const ctx=await mountShell({title:'Band media'});
if(ctx.role!=='full'){location.replace('/admin/plugverse/');throw new Error('Personal media access required');}
const root=document.querySelector('#band-media');
let assets=[],reviews=[],selected=null,filter='all',busy=false,dirty=false,pending=null;
const time=n=>n==null?'':Number(n).toFixed(2);
async function api(query='',body){const s=await getSession();const r=await fetch('/api/band-review'+query,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${s?.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Connection failed');return data;}
root.innerHTML=`<header class="ws-head"><span class="ws-kicker">Rubber Band / Media</span><h1>Keep the good moments.</h1><p>Watch, select and mark a range. Your originals stay in Drive.</p></header><p class="ws-note">Private owner preview. Bandmate access and automatic Drive refresh are not connected yet.</p><div id="media-message" role="status" aria-live="polite">Loading your footage…</div><div class="media-layout"><section class="ws-card"><label for="media-filter">Show</label><select id="media-filter"><option value="all">All footage</option><option value="favorite">Favorites</option><option value="unreviewed">To review</option><option value="reject">Rejected</option></select><div id="media-list"></div></section><section class="ws-card" id="media-detail"><h2>Select a clip</h2><p>Only the selected video loads.</p></section></div>`;
const message=t=>document.querySelector('#media-message').textContent=t;
const currentReview=()=>reviews.find(r=>r.asset_id===selected)||{revision:0,verdict:'unreviewed',note:'',time_seconds:null,trim_start:null,trim_end:null};
function list(){document.querySelector('#media-list').innerHTML=assets.filter(a=>filter==='all'||(reviews.find(r=>r.asset_id===a.id)?.verdict||'unreviewed')===filter).map(a=>`<button class="media-item ${selected===a.id?'selected':''}" data-asset="${a.id}"><strong>${esc(a.gig)}</strong><span>${esc(a.name)}</span><small>${esc(reviews.find(r=>r.asset_id===a.id)?.verdict||'unreviewed')} · ${a.proxy_path?'Preview ready':'Open in Drive'}</small></button>`).join('')||'<p>No clips in this view.</p>';document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{if(busy)return;if(dirty){message('Save your review or reload the saved version before switching clips.');return;}show(b.dataset.asset);});}
async function show(id){selected=id;pending=null;dirty=false;list();const a=assets.find(a=>a.id===id),r=currentReview();const detail=document.querySelector('#media-detail');
 detail.innerHTML=`<div class="media-title"><div><h2>${esc(a.gig)}</h2><p>${esc(a.name)}</p></div><a href="https://drive.google.com/file/d/${encodeURIComponent(a.drive_file_id)}/view" target="_blank" rel="noopener">Original ↗</a></div>${a.proxy_path?'<video id="review-video" controls playsinline preload="metadata"></video>':`<iframe class="drive-preview" title="Google Drive preview of ${esc(a.name)}" src="https://drive.google.com/file/d/${encodeURIComponent(a.drive_file_id)}/preview" loading="lazy" allow="fullscreen" referrerpolicy="no-referrer"></iframe><p class="ws-note">Drive preview uses your existing Google access. If it cannot play here, open Original above. Enter moments and ranges manually for this clip; automatic playback markers require a prepared preview.</p>`}<form id="review-form"><div class="media-fields"><label>Selection<select id="verdict"><option value="unreviewed">To review</option><option value="favorite">Favorite</option><option value="reject">Reject</option></select></label><label>Moment (seconds)<input id="moment" type="number" min="0" step="0.01" value="${time(r.time_seconds)}"></label></div><button type="button" data-needs-video id="mark-moment">Use playback position</button><label class="media-note">Your note<textarea id="review-note" maxlength="4000" rows="3" placeholder="What works here?">${esc(r.note)}</textarea></label><div class="media-fields"><label>Trim start (seconds)<input id="trim-start" type="number" min="0" step="0.01" value="${time(r.trim_start)}"></label><label>Trim end (seconds)<input id="trim-end" type="number" min="0" step="0.01" value="${time(r.trim_end)}"></label></div><div class="ws-tools"><button type="button" data-needs-video id="mark-start">Start here</button><button type="button" data-needs-video id="mark-end">End here</button><button type="button" data-needs-video id="preview-range">Play range</button></div><div class="ws-tools"><button type="submit" id="save-review">Save review</button><button type="button" id="reload-review">Reload saved version</button><button type="button" id="export-select">Download edit notes</button></div><p class="ws-note" id="review-revision">Revision ${r.revision} ${r.updated_at?'· saved '+esc(new Date(r.updated_at).toLocaleString()):'· not reviewed'}. Video rendering is not connected; edit notes contain the original link and trim range.</p></form>`;
 document.querySelector('#verdict').value=r.verdict;
 const form=document.querySelector('#review-form'),video=document.querySelector('#review-video');
 form.querySelectorAll('[data-needs-video]').forEach(el=>el.disabled=!video);
 form.oninput=()=>{dirty=true;pending=null;};
 const stamp=id=>{if(!video)return;document.querySelector(id).value=video.currentTime.toFixed(2);dirty=true;pending=null;};
 document.querySelector('#mark-moment').onclick=()=>stamp('#moment');document.querySelector('#mark-start').onclick=()=>stamp('#trim-start');document.querySelector('#mark-end').onclick=()=>stamp('#trim-end');
 document.querySelector('#preview-range').onclick=()=>{if(!video)return;const start=Number(document.querySelector('#trim-start').value),end=Number(document.querySelector('#trim-end').value);if(!(end>start)){message('Set an end after the start.');return;}video.currentTime=start;video.ontimeupdate=()=>{if(video.currentTime>=end){video.pause();video.ontimeupdate=null;}};video.play().catch(()=>message('Press Play to preview the range.'));};
 document.querySelector('#reload-review').onclick=async()=>{try{await load();await show(id);message('Saved review loaded.');}catch(e){message(e.message);}};
 document.querySelector('#export-select').onclick=()=>{const saved=currentReview();const blob=new Blob([JSON.stringify({original:`https://drive.google.com/file/d/${a.drive_file_id}/view`,name:a.name,gig:a.gig,review:saved},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='rubber-edit-notes.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Downloaded saved edit notes. The original was not changed.');};
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;message('Saving and verifying…');form.querySelectorAll('input,textarea,select,button').forEach(el=>el.disabled=true);const num=id=>document.querySelector(id).value===''?null:Number(document.querySelector(id).value);pending??={asset:id,revision:currentReview().revision,operation:crypto.randomUUID(),verdict:document.querySelector('#verdict').value,note:document.querySelector('#review-note').value,time:num('#moment'),start:num('#trim-start'),end:num('#trim-end')};try{const result=await api('',pending);reviews=reviews.filter(x=>x.asset_id!==id).concat(result.review);dirty=false;pending=null;list();document.querySelector('#review-revision').textContent='Revision '+result.review.revision+' · saved and verified';message('Saved and verified.');}catch(e){message(e.message);}finally{busy=false;form.querySelectorAll('input,textarea,select,button').forEach(el=>el.disabled=el.hasAttribute('data-needs-video')&&!video);}};
 if(video)try{const stream=await api('?asset='+id);if(selected===id)video.src=stream.url;}catch(e){message(e.message);}
}
async function load(){const data=await api();assets=data.assets;reviews=data.reviews;list();}
document.querySelector('#media-filter').onchange=e=>{filter=e.target.value;list();};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(isLocalDemo()){message('Design preview. Sign in to the private preview to load and save real footage.');}else try{await load();message(assets.length+' clips · private previews · originals unchanged');}catch(e){message(e.message);}
