import {mountShell,isLocalDemo} from '/admin/_shell/admin-shell.js';
import {getSession} from '/admin/_shell/supabase.js';
import {esc} from '/admin/_shell/ui.js';
import {cashAccounts} from '/admin/_shell/workspace-model.mjs';
const ctx=await mountShell({title:'Money'}),app=document.querySelector('#money');
if(!['full','plugverse'].includes(ctx.role)){location.replace('/admin/acquisition/');throw Error('Financial access required');}
const usd=n=>n==null||!Number.isFinite(Number(n))?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n));
const date=s=>s?new Date(s.length===10?s+'T12:00:00':s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'date missing';
const title='<header class="ws-head"><span class="ws-kicker">Admin / Money</span><h1>Know what is actually there.</h1><p>Cash first. Funding history and investments stay separate.</p></header>';
app.innerHTML=title+'<p role="status">Reading balances and their sources…</p>';
try{
 if(isLocalDemo())throw Error('Design preview. Sign in to inspect current balances; no sample money figures are shown.');
 const session=await getSession();const response=await fetch('/api/money-overview',{headers:{Authorization:'Bearer '+session.access_token},cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);
 const note=data.confirmation?.content||'',reported=data.confirmation?.reported_at;
 const personal=cashAccounts(data.personal);
 const accounts=(rows,personal=false)=>rows.length?rows.map(r=>`<li><div><strong>${esc(personal?r.account.replaceAll('_',' '):r.account_label)}</strong><small>${esc(r.source||'Source not recorded')} · ${esc(date(r.as_of))}${r.balance_kind?' · '+esc(r.balance_kind):''}</small>${Date.now()-Date.parse(r.as_of)>48*3600000?'<small>Older than 48 hours — verify before relying on this amount.</small>':''}</div><strong>${usd(r.balance)}</strong></li>`).join(''):'<li>No recorded balance returned. This is not zero.</li>';
 const debt=/Outstanding debts \/ liabilities: \$0, user-confirmed/.test(note),fund=/1789 Venture Fund: fully spent; actual remaining allocation is \$0/.test(note);
 app.innerHTML=title+`<div class="ws-grid"><section class="ws-card"><h2>PlugVerse bank cash</h2><ul class="ws-list">${accounts(data.bank)}</ul><p class="ws-note">Bank snapshots, not an estimate from grant spending. The original Luby award is not added again.</p></section>${ctx.role==='full'?`<section class="ws-card"><h2>Personal cash</h2><ul class="ws-list">${accounts(personal,true)}</ul><p class="ws-note">Checking and savings only. <a href="/admin/finance/investments.html">Investments</a> are separate.</p></section>`:''}<section class="ws-card ws-wide"><h2>What needs reconciling</h2><p>Funding-tag totals are incomplete and must not be treated as available cash.</p>${fund?`<p><strong>1789: fully spent — $0 remaining.</strong> You confirmed this ${date(reported)}. The ledger still needs the corresponding transactions matched; no balancing expense has been invented.</p>`:''}${debt?`<p><strong>No outstanding debt, card balance or unreimbursed business expenses reported.</strong> Your confirmation is dated ${date(reported)}; it is not a live card feed.</p>`:''}<div class="ws-tools"><a href="/admin/finance/transactions.html">Review transactions</a><a href="/admin/integrations/">Check bank updates</a><a href="/admin/finance/overview.html">Detailed ledger reports</a></div>${data.confirmation?`<details><summary>Read the confirmation and discrepancies</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;margin-top:18px">${esc(note)}</pre><p class="ws-provenance">${esc(data.confirmation.source)} · mirror updated ${esc(date(data.confirmation.mirrored_at))}</p></details>`:'<p class="ws-note">The dated vault confirmation is unavailable for this session. No manual amounts are substituted.</p>'}</section><section class="ws-card ws-wide"><h2>Recent recorded activity</h2><ul class="ws-list">${data.recent.map(r=>`<li><div><strong>${esc(r.description||'Transaction')}</strong><small>${esc(date(r.date))} · ${esc(r.entity||'Unclassified')}${!r.funding_source?' · funding source not assigned':''}</small></div><span>${r.type==='expense'?'−':''}${usd(r.amount)}</span></li>`).join('')||'<li>No activity returned by the ledger.</li>'}</ul><p class="ws-note">Recorded transactions may have gaps. This list does not certify complete bank or card coverage.</p></section></div>`;
}catch(e){app.innerHTML=title+'<section class="ws-card"><h2>Source unavailable</h2><p>'+esc(e.message)+'</p><a href="/admin/finance/overview.html">Open existing ledger reports</a></section>';}
