import {mountShell} from '/admin/_shell/admin-shell.js';
import {sb,requireFullAdminOrRedirect} from '/admin/_shell/supabase.js';
import {esc,pageHead} from '/admin/_shell/ui.js';
import {GOALS,safeURL,searchReferences,summarizeReferences,makeBrief} from '/admin/_shell/research-model.mjs';
if(!(await requireFullAdminOrRedirect()))throw Error('Full admin required');
await mountShell({title:'Content research'});
const app=document.querySelector('#app');
app.innerHTML=pageHead('Content','Find the reference. Make it mine.')+`<p><a href="/admin/content/">All posts</a> · <a href="/admin/schedule/">Current plan</a> · <a href="/admin/content/intent">Brand & next steps</a></p><p id="coverage">Loading source evidence…</p><div class="research-filters"><input id="query" aria-label="Search references" placeholder="What am I making? Try planning, music, comparison…"><select id="topic" aria-label="Topic"><option value="">All topics</option></select><select id="mechanism" aria-label="Opening mechanism"><option value="">All openings</option></select><select id="format-filter" aria-label="Format"><option value="">All formats</option><option>M01</option><option>M06</option><option>M09</option></select><select id="metric" aria-label="Public metric"><option value="views">Views</option><option value="plays">Plays</option></select></div><details><summary>Compare the selected sample</summary><p>Historical snapshots across creators and post ages. These associations do not establish what caused performance. Small samples are directional; missing data stays unknown.</p><div id="stats" class="research-stats"></div></details><div class="research-layout"><section id="results" class="research-list"></section><form id="brief" class="sv-card research-brief"><h2>What changes in my piece?</h2><label>Existing piece<select id="piece" required><option value="">Choose from the current plan</option></select></label><label>What is it for?<select id="goal">${Object.entries(GOALS).map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select></label><label>Format<select id="format"><option>M01</option><option>M06</option><option>M09</option></select></label><label>My actual idea<textarea id="intent" required placeholder="What happened, and what I want this to feel like."></textarea></label><label>What am I borrowing?<textarea id="adaptation" required placeholder="The exact opening, story beat, or shot choice. Keep my experience and voice."></textarea></label><label>What does the ending deliver?<textarea id="payoff" required placeholder="How the ending pays off the opening."></textarea></label><label>Where should someone go next? (optional)<input id="cta" type="url" placeholder="https://…"></label><p id="selected">No references chosen.</p><button class="btn" type="submit">Save to this piece</button><p id="saved" role="status" aria-live="polite"></p><p class="research-meta">This saves research, not approval or a publication. Visual delivery and the final script still need review.</p></form></div>`;
let rows=[],plans=[],chosen=new Set(),visible=[],page=30;
const el=id=>document.getElementById(id);
try{
 const [library,plan]=await Promise.all([sb.from('vault_documents').select('content,updated_at').eq('path','Projects/personal-brand/reel-intel/admin-research.json').single(),sb.from('content_plan').select('id,piece,lane,source_path,note,research_brief,research_updated_at,status').order('day',{ascending:false}).limit(150)]);
 if(library.error||plan.error)throw library.error||plan.error;
 const data=JSON.parse(library.data.content);rows=data.records;plans=plan.data;
 el('coverage').textContent=`${rows.length} source references · ${rows.filter(r=>r.analysis).length} Jev analyses · updated ${new Date(library.data.updated_at).toLocaleString()}. Labels describe speech; they don't judge the film or predict views.`;
 for(const dimension of ['topic','mechanism']){for(const value of [...new Set(rows.map(r=>r.analysis?.labels?.[dimension]?.value).filter(Boolean))].sort())el(dimension).insertAdjacentHTML('beforeend',`<option value="${esc(value)}">${esc(value.replaceAll('_',' '))}</option>`);}
 for(const p of plans)el('piece').insertAdjacentHTML('beforeend',`<option value="${p.id}">${esc(p.piece)} · ${esc(p.lane)}</option>`);
 draw();
}catch(e){el('coverage').textContent='Research could not load. '+(e.message||'Try again.');el('coverage').classList.add('research-error');el('brief').querySelector('button').disabled=true;}
function draw(){
 visible=searchReferences(rows,{query:el('query').value,topic:el('topic').value,mechanism:el('mechanism').value,format:el('format-filter').value});
 const metric=el('metric').value;
 el('stats').innerHTML=summarizeReferences(visible,metric).map(g=>`<div>${esc(g.mechanism)}<br>median ${Math.round(g.median).toLocaleString()} ${metric}<br>${g.n} examples</div>`).join('')||'No comparable dated values in this selection.';
 el('results').innerHTML=visible.slice(0,page).map(r=>{const a=r.analysis,s=r.snapshot,url=safeURL(r.url);return `<article class="sv-card research-card"><div class="research-meta">${esc(r.platform)} · @${esc(r.creator)} · ${esc(r.format||'format unreviewed')}</div><blockquote>${esc(r.opening||'Visual reference; no verified spoken opening')}</blockquote><div class="research-tags">${Object.entries(a?.labels||{}).map(([k,v])=>`<span title="${esc(k)}; model confidence, not performance probability">${esc(v.value.replaceAll('_',' '))} · ${Math.round(v.confidence*100)}%</span>`).join('')}</div><p class="research-meta">${Number.isFinite(s?.[metric])?s[metric].toLocaleString()+' '+metric:'Unknown '+metric} · observed ${esc(s?.as_of||'date unknown')}<br>${esc(r.source||r.review?.review_basis||'No transcript source')}</p><details><summary>Read source and script structure</summary><pre>${esc(r.transcript||JSON.stringify(r.review,null,2))}</pre>${(a?.anatomy||[]).map(x=>`<p><strong>${esc(x.value)}</strong> · ${esc(x.text)}</p>`).join('')}</details><p>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open original</a>`:''}</p><button type="button" class="btn" data-ref="${esc(r.id)}" aria-pressed="${chosen.has(r.id)}">${chosen.has(r.id)?'Chosen':'Use as reference'}</button></article>`;}).join('')||'<p>No references match. Try a broader phrase.</p>';
 if(visible.length>page)el('results').insertAdjacentHTML('beforeend','<button id="more-research" class="btn">Show more references</button>');
 el('more-research')?.addEventListener('click',()=>{page+=30;draw();});
 el('results').querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>{const id=b.dataset.ref;if(chosen.has(id))chosen.delete(id);else if(chosen.size<3)chosen.add(id);else{el('saved').textContent='Keep one to three useful references.';return;}el('selected').textContent=[...chosen].join(' · ')||'No references chosen.';draw();});
}
for(const id of ['query','topic','mechanism','format-filter','metric'])el(id).addEventListener(id==='query'?'input':'change',()=>{page=30;draw();});
el('piece').onchange=()=>{const p=plans.find(p=>String(p.id)===el('piece').value),b=p?.research_brief;chosen=new Set((b?.references||[]).map(r=>r.id));el('intent').value=b?.raw_intent||p?.note||p?.piece||'';el('adaptation').value=b?.adaptation||'';el('payoff').value=b?.payoff||'';el('cta').value=b?.cta_destination||'';el('goal').value=b?.goal||(p?.lane==='plugverse'?'plugverse':'connection');el('format').value=b?.format||'M01';el('selected').textContent=[...chosen].join(' · ')||'No references chosen.';draw();};
el('brief').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const p=plans.find(p=>String(p.id)===el('piece').value);const brief=makeBrief({plan:p,goal:el('goal').value,cta:el('cta').value,adaptation:el('adaptation').value,payoff:el('payoff').value,rawIntent:el('intent').value,format:el('format').value,references:rows.filter(r=>chosen.has(r.id))});const at=new Date().toISOString();let q=sb.from('content_plan').update({research_brief:brief,research_updated_at:at}).eq('id',p.id);q=p.research_updated_at?q.eq('research_updated_at',p.research_updated_at):q.is('research_updated_at',null);const {data,error}=await q.select('id,research_brief,research_updated_at');if(error)throw error;if(data.length!==1)throw Error('This piece changed elsewhere. Reload before saving.');Object.assign(p,data[0]);el('saved').textContent='Saved to the existing piece. The next vault research sync brings this into drafting.';}catch(e){el('saved').textContent=e.message||'Could not save. Your notes are still here.';}finally{button.disabled=false;}};
