"""Small additions to the existing portfolio generator; no new design/build stack."""
import html,json,pathlib,re
ROOT=pathlib.Path(__file__).resolve().parents[1]
E=html.escape
def page(title,body):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} / Cooper Delo</title><link rel="stylesheet" href="/assets/brand.css"><meta name="description" content="Films, motion and product by Cooper Delo. Build something, work together, or plan your next film."></head><body class="brand-page"><nav class="brand-nav"><a href="/">Cooper Delo</a><a href="/#work">See the work</a></nav><main class="brand-main">{body}</main><script src="/assets/brand.js" defer></script></body></html>'''
def build():
 b=json.loads((ROOT/'content/brand.json').read_text(encoding='utf-8'))
 inquiry=f'''<h1>What are you building?</h1><p class="lede">{E(b['opportunity'])}</p><div class="proof-links"><a href="/work/plugverse-launch-film">Watch the launch film</a><a href="/work/plugverse-product">See the product</a><a href="/work/bioswap">See the motion work</a></div><div class="brand-grid"><section><h2>Something we can actually make.</h2><p>A short film for a launch. Motion that makes a product easier to understand. Help turning an idea into something people can use.</p><p>Tell me the goal and what you have already. We can figure out the right scope from there.</p><p>{E(b['career'])}</p><a href="/resume">My experience</a><h2>Booking your own shows?</h2><p>{E(b['plugverse'])}</p><a href="https://plugverse.app/?utm_source=cooperdelo&utm_medium=portfolio&utm_campaign=artist_workflow">See PlugVerse</a></section><form id="inquiry"><label>What did you have in mind?<select name="kind"><option>Film or motion project</option><option>Product or creative collaboration</option><option>Summer 2027 opportunity</option></select></label><label>What are you working on?<textarea name="brief" required maxlength="3000" placeholder="The project, who it's for, and where you need help."></textarea></label><label>When?<input name="timing" maxlength="120" placeholder="A rough timeline is fine."></label><label>Budget or role (optional)<input name="budget" maxlength="180"></label><button class="brand-button">Prepare an email</button><p class="brand-note">This prepares a draft in your email app. Nothing is sent or submitted here.</p><div id="draft-ready" hidden role="status"><a class="brand-button" id="draft-link">Open email draft</a><p>Review it, add your details, and send when you're ready.</p></div></form></div>'''
 (ROOT/'work-with-me.html').write_text(page('Work with me',inquiry),encoding='utf-8')
 steps=[('idea','The actual idea','What happened? What do you want someone to feel?'),('opening','The first thing we see or hear','Give someone a reason to keep watching.'),('question','What are we waiting to find out?','A real unanswered question, not a vague promise.'),('change','What changes?','The attempt, complication, or detail that moves it forward.'),('payoff','What does the ending give us?','Answer the question you opened. You do not need a life lesson.'),('shots','What do you need to shoot?','List the action, framing, location, and sound. Use what you actually have.'),('next_step','What happens after someone watches?','Come back, see the work, use the product, or simply enjoy it.')]
 planner='<h1>Get the idea out of your head.</h1><p class="lede">A simple plan for the next film you want to make. Fill in what matters, download it, and go shoot.</p><p>No account. No email gate. Your notes stay in this browser.</p><form id="planner">'+''.join(f'<section class="shot"><h2>{E(title)}</h2><label for="{key}">{E(prompt)}</label><textarea id="{key}" name="{key}" maxlength="5000"></textarea></section>' for key,title,prompt in steps)+'</form><button id="download-plan" class="brand-button">Download my plan</button><button id="print-plan" class="brand-button">Print</button><p id="planner-status" role="status" class="brand-note"></p><p><a href="/work/plugverse-launch-film">See a film I made</a> · <a href="/work-with-me">Make something together</a></p>'
 (ROOT/'resources').mkdir(exist_ok=True);(ROOT/'resources/film-plan.html').write_text(page('Film planner',planner),encoding='utf-8')
 for slug,notes in b['cases'].items():
  p=ROOT/'work'/f'{slug}.html';s=p.read_text(encoding='utf-8');block='<section class="case-notes" aria-label="About the work">'+''.join(f'<div><h2>{E(n["title"])}</h2><p>{E(n["body"])}</p></div>' for n in notes)+'</section>'
  s=re.sub(r'<section class="case-notes" aria-label="About the work">.*?</section><section class="brand-home">.*?</section>', '', s, flags=re.S)
  if 'aria-label="About the work"' not in s:s=s.replace('</main>',block+'<section class="brand-home"><p>Working on something?</p><a class="brand-button" href="/work-with-me">Tell me about it</a></section></main>')
  if '/assets/brand.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/brand.css"></head>')
  p.write_text(s,encoding='utf-8')
 p=ROOT/'index.html';s=p.read_text(encoding='utf-8');block=f'<section class="brand-home" id="work-together"><h2>Let’s make something.</h2><p>{E(b["opportunity"])}</p><a class="brand-button" href="/work-with-me">Tell me what you’re building</a><a href="/resources/film-plan">Plan your next film</a></section>'
 s=re.sub(r'<section class="brand-home" id="work-together">.*?</section>', '', s, flags=re.S)
 if 'id="work-together"' not in s:s=s.replace('</main>',block+'</main>')
 if '/assets/brand.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/brand.css"></head>')
 s=s.replace('href="https://cal.com/cooper-delo1" target="_blank" rel="noreferrer">Book a call','href="/work-with-me">Work with me');p.write_text(s,encoding='utf-8')
 print('Built work inquiry, film planner, and two case-study additions.')
if __name__=='__main__':build()
