"""Turn a fresh export of the Claude acquisition board into one SQL file for the admin database.

    python scripts/import-acquisition-board.py <export_dir> <out.sql> [--who u_xxx=email:Name ...]

The export dir is what ArtifactData writes with out_dir: leads/, drafts/, conversations/, activity/,
runs/, lanes/, venue_acts/ and reference/artists.json, one JSON document per file.

Run it at cutover, on an export taken after the board was set to view-only, so nothing written to
the board afterwards is lost. The SQL upserts, so running it twice is harmless. It never deletes.
"""
import argparse
import json
import re
from pathlib import Path

LEAD_COLS = ("name", "platform", "bucket", "status", "area", "followers", "queue_day", "queue_order",
             "finder_verdict", "draft_verdict", "owner")
STATUSES = {"new", "approved", "contacted", "replied", "signed_up", "rejected"}


def q(v):
    """SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(int(v)) if float(v).is_integer() else str(v)
    return "'" + str(v).replace("'", "''") + "'"


def j(v):
    return q(json.dumps(v, ensure_ascii=False, sort_keys=True)) + "::jsonb"


def docs(folder):
    p = Path(folder)
    return [json.loads(f.read_text(encoding="utf-8")) for f in sorted(p.glob("*.json"))] if p.is_dir() else []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export_dir")
    ap.add_argument("out")
    ap.add_argument("--who", nargs="*", default=[], help="artifact user id mapped to email:Name")
    a = ap.parse_args()
    root = Path(a.export_dir)
    who = {}
    for m in a.who:
        uid, rest = m.split("=", 1)
        email, _, name = rest.partition(":")
        who[uid] = (email, name or email)
    email_of = lambda uid: who.get(uid or "", ("", ""))[0]
    name_of = lambda uid: who.get(uid or "", ("", ""))[1]

    out = ["-- Generated by scripts/import-acquisition-board.py. Upserts only.", "begin;"]

    leads = docs(root / "leads")
    for d in leads:
        h = d["handle"].strip().lower()
        if not re.fullmatch(r"[a-z0-9._-]{1,80}", h):
            raise SystemExit(f"unexpected handle: {h!r}")
        row = {k: d.get(k) for k in LEAD_COLS}
        row["status"] = row["status"] if row["status"] in STATUSES else "new"
        row["followers"] = int(row.get("followers") or 0)
        for k in ("name", "platform", "bucket", "area", "owner"):
            row[k] = row[k] or ""
        if row["finder_verdict"] not in ("right", "wrong"):
            row["finder_verdict"] = None
        if row["draft_verdict"] not in ("approved", "rejected"):
            row["draft_verdict"] = None
        cols = ["handle", *LEAD_COLS, "data", "created_at", "updated_at", "updated_by"]
        vals = [q(h), *(q(row[k]) for k in LEAD_COLS), j(d),
                q(d.get("created_at") or "2026-09-27T00:00:00Z"),
                q(d.get("updated_at") or d.get("created_at") or "2026-09-27T00:00:00Z"),
                q(email_of(d.get("updated_by")))]
        sets = ", ".join(f"{c} = excluded.{c}" for c in cols[1:])
        out.append(f"insert into public.acq_leads ({', '.join(cols)}) values ({', '.join(vals)}) on conflict (handle) do update set {sets};")

    for f in sorted((root / "conversations").glob("*.json")) if (root / "conversations").is_dir() else []:
        d = json.loads(f.read_text(encoding="utf-8"))
        out.append(
            "insert into public.acq_conversations (source_id, at, by_email, by_name, name, handle, kind, channel, date, outcome, quote, notes, tags, next_step, next_date) values ("
            + ", ".join([q(f.stem), q(d.get("at")), q(email_of(d.get("by"))), q(name_of(d.get("by"))), q(d.get("name") or "?"),
                         q(d.get("handle") or ""), q(d.get("kind") or ""), q(d.get("channel") or ""), q(d.get("date") or None),
                         q(d.get("outcome") or ""), q(d.get("quote") or ""), q(d.get("notes") or ""),
                         q("{" + ",".join('"' + t.replace('"', "") + '"' for t in d.get("tags") or []) + "}") + "::text[]",
                         q(d.get("next") or ""), q(d.get("next_date") or None)]) + ") on conflict (source_id) do nothing;")

    for f in sorted((root / "activity").glob("*.json")) if (root / "activity").is_dir() else []:
        d = json.loads(f.read_text(encoding="utf-8"))
        out.append("insert into public.acq_activity (source_id, at, by_email, by_name, kind, handle, detail) values ("
                   + ", ".join([q(f.stem), q(d.get("at")), q(email_of(d.get("by"))), q(name_of(d.get("by"))), q(d.get("kind") or "edit"),
                                q(d.get("handle") or ""), q(d.get("detail") or "")]) + ") on conflict (source_id) do nothing;")

    ref = {
        "drafts": {f.stem: json.loads(f.read_text(encoding="utf-8")) for f in sorted((root / "drafts").glob("*.json"))},
        "runs": docs(root / "runs"),
        "lanes": docs(root / "lanes"),
        "venue_acts": docs(root / "venue_acts"),
    }
    art = root / "reference" / "artists.json"
    if art.exists():
        ref["artists"] = json.loads(art.read_text(encoding="utf-8"))
    for k, v in ref.items():
        out.append(f"insert into public.acq_reference (key, data, updated_at) values ({q(k)}, {j(v)}, now()) on conflict (key) do update set data = excluded.data, updated_at = now();")

    out.append("commit;")
    Path(a.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(leads)} leads, {len(docs(root / 'conversations'))} conversations, {len(docs(root / 'activity'))} activity, reference: {', '.join(ref)} -> {a.out}")


if __name__ == "__main__":
    main()
